### ISSUE TITLE
markup: direct_url

### ISSUE THREAD

**Issue by rowanflack** [rbuchberger/jekyll_picture_tag#174] opened 2020-04-06 05:53 UTC
RE: markup: direct_url
Issue with outputting generated image and url. 

RE: steps to reproduce
If I add a new image to the front-matter it won't trigger the markup_preset and generate the new image. However it will return the correct url.

If I change the name of the markup_preset and save, it will rebuild and trigger the markup_preset and output the new image.

Are you replicate and confirm this issue?

RE: _data/picture.yaml
media_presets:
  mobile: 'min-width: 768px'
markup_presets:
  default:
    markup: data_auto
    formats: [webp, original]
    widths: [480, 768, 1024, 1440]
    sizes:
      mobile: 60vw, 100vw
    attributes:
      img: 'class="img lazyload"'
  direct-url:
    markup: direct_url
    fallback_format: original
    fallback_width: 800

**Comment by rbuchberger** [comment] 2020-04-06 17:52
I'm sorry, I don't entirely understand what you're trying to do. How are you using the front-matter image?

**Comment by rowanflack** [comment] 2020-04-06 22:40
Sorry I wasn't sure if I'd been entirely clear. 

Front matter looks like this
testimonial:
 - image: lorum_ipsum.jpg
   heading: Lorum ipsum
 - image: blank.jpg
   heading: Blank

If i add a new entry (image and heading) to the above list or update an existing image it doesn't trigger the image generation of the direct-url markup preset above. 

However it does output the URL but the new/updated image is never generated.

HTML:
 {% picture direct-url {{ entry.image }} %}

**Comment by rbuchberger** [comment] 2020-04-28 09:20
Ok, thanks! I'll look into this and see if I can reproduce it.

**Comment by kslstn** [comment] 2020-05-16 13:21
Same here: no generated images for includes with these presets:

```
markup_presets:

  twitter-card:
    markup: direct_url
    formats: [original]
    fallback_width: 1024

  open-graph-size-l:
    markup: direct_url
    formats: [original]
    fallback_width: 1400

  open-graph-size-m:
    markup: direct_url
    formats: [original]
    fallback_width: 400
```
This used to work before.

**Comment by kslstn** [comment] 2020-05-16 14:19
I'm actually not 100% sure if this used to work before. Without the `markup: direct_url` option, images are rendered, so it can very well be that they were rendered while I was writing the preset with Jekyll's auto rebuild on. My workaround for now is to temporarily remove those lines from the preset to get the images to show up in my `/generated` directory, but of course this is prone to errors.

**Comment by rbuchberger** [comment] 2020-06-12 08:19
Hey, sorry I haven't moved on this issue at all. I haven't forgotten about it, I've just been busy. Next week I'll hopefully have some time to troubleshoot it. Thanks y'all for your patience!

**Comment by rbuchberger** [comment] 2020-07-06 14:58
Well, a week turned into almost a month. Sorry about that!

Turns out we weren't generating fallback images at all; direct_url just uses the fallback image code, which is why you guys noticed it then. That's embarassing, but it's fixed now.

**Closed** 2020-07-06 15:03 UTC
Labels: bug

**Comment by kslstn** [comment] 2020-07-06 19:35
Don't be embarrassed, you fixed it and I'm very happy about that. Thanks so much!
